collections:
  getting_started:
    output: true
    permalink: /docs/:name/
  services:
    output: true
    permalink: /docs/:name/
  languages_and_frameworks:
    output: true
    permalink: /docs/:name/
  documentation:
    output: true
    permalink: /docs/:name/
  api:
    output: true
    permalink: /api/:name/
defaults:
  - scope:
      path: ""
    values:
      layout: default
